language: node_js

node_js:
  - "7"

sudo: false

before_install:
  - npm --prefix=frontend/ config set spin false

install:
  - npm --prefix=frontend/ install -g bower
  - npm --prefix=frontend/ install
  - cd frontend && bower install && cd ..

script:
  - npm --prefix=frontend/ test

after_script:
  - cat ./frontend/coverage/lcov.info | ./frontend/node_modules/.bin/coveralls

env:
  global:
    - COVERAGE=true
